spring:
  application:
    name: userdata

  datasource:
    url: jdbc:mysql://mysql:3306/user_data
    username: rin
    password: llyjus
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  grpc:
    server:
      port: 9090